// ─── Wear History Store ───────────────────────────────────────────────────────
// Persists daily outfit / wear records to localStorage.
//
// Schema:  { [dateStr: "YYYY-MM-DD"]: WearRecord }
// WearRecord: {
//   itemIds:   string[]      — closet item IDs worn that day (item-1, item-2 …)
//   note:      string        — optional free-text memo
//   photoUrl:  string|null   — base64 data URI from camera/upload (stored locally)
//   updatedAt: string        — ISO timestamp of last save
// }

const WEAR_HISTORY_KEY = "trunkroom_wear_history_v1";
const SEED_KEY         = "trunkroom_wear_history_seeded_v2"; // bump version to re-seed

// ─── Helpers ──────────────────────────────────────────────────────────────────

function loadStore() {
  try {
    const raw = localStorage.getItem(WEAR_HISTORY_KEY);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

function saveStore(data) {
  try {
    localStorage.setItem(WEAR_HISTORY_KEY, JSON.stringify(data));
  } catch {
    // Storage quota exceeded — silently skip
  }
}

/** Format a Date as local YYYY-MM-DD (avoids UTC off-by-one). */
export function localDateStr(d) {
  const y  = d.getFullYear();
  const m  = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${dd}`;
}

/** Today as local YYYY-MM-DD. */
export function todayStr() {
  return localDateStr(new Date());
}

// ─── Seed demo data ───────────────────────────────────────────────────────────
// Seeds 14 days of rich records (with real item IDs) so every analytics section
// shows meaningful content on first launch.
// Item IDs are item-1…item-132 (generated by mockClosetData in order).

const SEED_PATTERN = [
  { offset: 0,  itemIds: ["item-1", "item-6",  "item-11"],       note: "데일리 오피스룩" },
  { offset: 1,  itemIds: ["item-1", "item-15", "item-22"],       note: "" },
  { offset: 2,  itemIds: ["item-2", "item-11", "item-28"],       note: "캐주얼 데이" },
  { offset: 4,  itemIds: ["item-3", "item-22", "item-30"],       note: "" },
  { offset: 5,  itemIds: ["item-1", "item-15", "item-6"],        note: "편한 출근룩" },
  { offset: 7,  itemIds: ["item-5", "item-11", "item-30"],       note: "" },
  { offset: 8,  itemIds: ["item-2", "item-22", "item-28"],       note: "미니멀 데이" },
  { offset: 9,  itemIds: ["item-1", "item-6",  "item-28"],       note: "" },
  { offset: 11, itemIds: ["item-3", "item-15", "item-11"],       note: "주말 나들이" },
  { offset: 13, itemIds: ["item-2", "item-11", "item-30"],       note: "" },
];

function maybeSeedDemoData() {
  if (localStorage.getItem(SEED_KEY)) return;

  // Remove stale v1 seed so we start fresh
  localStorage.removeItem(WEAR_HISTORY_KEY);
  localStorage.removeItem("trunkroom_wear_history_seeded_v1");

  const store = {};
  const base  = new Date();
  base.setHours(12, 0, 0, 0);

  SEED_PATTERN.forEach(({ offset, itemIds, note }) => {
    const d = new Date(base);
    d.setDate(d.getDate() - offset);
    store[localDateStr(d)] = {
      itemIds,
      note,
      photoUrl:  null,
      updatedAt: d.toISOString(),
    };
  });

  saveStore(store);
  localStorage.setItem(SEED_KEY, "1");
}

// Run once at module load
maybeSeedDemoData();

// ─── CRUD ─────────────────────────────────────────────────────────────────────

/** Returns all records as { [dateStr]: WearRecord }. */
export function getAllWearHistory() {
  return loadStore();
}

/** Returns the record for a specific date (YYYY-MM-DD) or null. */
export function getWearRecord(dateStr) {
  return loadStore()[dateStr] ?? null;
}

/** Save / update a wear record for a specific date. */
export function saveWearRecord(dateStr, { itemIds = [], note = "", photoUrl = null } = {}) {
  const store = loadStore();
  store[dateStr] = { itemIds, note, photoUrl, updatedAt: new Date().toISOString() };
  saveStore(store);
}

/** Delete a wear record for a specific date. */
export function deleteWearRecord(dateStr) {
  const store = loadStore();
  delete store[dateStr];
  saveStore(store);
}

/** Returns dates that have records, sorted newest-first. */
export function getRecordedDates() {
  return Object.keys(loadStore()).sort((a, b) => b.localeCompare(a));
}

// ─── Stats ────────────────────────────────────────────────────────────────────

/** Returns { totalDays, totalItems, streak } for the habit UI. */
export function getWearStats() {
  const store = loadStore();
  const dates = Object.keys(store).sort();

  const totalDays  = dates.length;
  const totalItems = dates.reduce((sum, d) => sum + (store[d]?.itemIds?.length ?? 0), 0);

  // Streak: consecutive days going backwards from today.
  // If today is not yet recorded, start counting from yesterday.
  const base = new Date();
  base.setHours(12, 0, 0, 0);

  let streak = 0;
  for (let offset = 0; offset < 365; offset++) {
    const d   = new Date(base);
    d.setDate(d.getDate() - offset);
    const key = localDateStr(d);

    if (store[key]) {
      streak++;
    } else if (offset === 0) {
      // Today not recorded yet — continue looking backwards
    } else {
      break; // gap found
    }
  }

  return { totalDays, totalItems, streak };
}

// ─── Analytics ────────────────────────────────────────────────────────────────

/**
 * Returns a Map<itemId, wearCount> built from all recorded outfit data.
 * Useful for "자주 입은 옷" and "오랫동안 안 입은 옷" modules.
 */
export function getItemWearFrequency() {
  const store = loadStore();
  const freq  = new Map();
  Object.values(store).forEach(({ itemIds = [] }) => {
    itemIds.forEach((id) => freq.set(id, (freq.get(id) ?? 0) + 1));
  });
  return freq;
}

/**
 * Returns a Map<itemId, lastWornDateStr> — the most recent date each item
 * appeared in a wear record.
 */
export function getItemLastWornDates() {
  const store = loadStore();
  const last  = new Map();
  // Iterate dates oldest→newest so we always keep the latest date
  Object.keys(store)
    .sort()
    .forEach((dateStr) => {
      (store[dateStr].itemIds ?? []).forEach((id) => last.set(id, dateStr));
    });
  return last;
}

/**
 * Returns the last N recorded days (newest first), each as
 * { dateStr, itemIds, note, photoUrl }.
 */
export function getRecentRecords(n = 7) {
  const store = loadStore();
  return Object.keys(store)
    .sort((a, b) => b.localeCompare(a))
    .slice(0, n)
    .map((dateStr) => ({ dateStr, ...store[dateStr] }));
}
