/**
 * imageAssetService.js
 * ─────────────────────────────────────────────────────────────────
 * Provides typed, categorized access to the processed local image
 * library generated by scripts/process-images.py.
 *
 * All images live in:
 *   /public/assets/images/items/   → product shots (no people)
 *   /public/assets/images/coordi/  → outfit/style images (face-cropped)
 *
 * Metadata source: src/constants/imageAssets.json
 *
 * Usage examples:
 *
 *   import {
 *     getItemImages,
 *     getCoordinateImages,
 *     getItemsByCategory,
 *     getRandomItems,
 *     getRandomCoordi,
 *     searchItemsByBrand,
 *   } from "@/services/imageAssetService";
 *
 *   const tops    = getItemsByCategory("tops");
 *   const outfits = getRandomCoordi(10);
 *   const vans    = searchItemsByBrand("반스");
 */

import assetManifest from "../constants/imageAssets.json";

// ─── Types (JSDoc) ────────────────────────────────────────────────────────────

/**
 * @typedef {Object} ItemRecord
 * @property {string}   id
 * @property {"item"}   type
 * @property {string}   source           - "musinsa_product"
 * @property {string}   app_url          - Vite-served URL e.g. "/assets/images/items/001_xxx.jpg"
 * @property {string}   original_path
 * @property {string}   processed_path
 * @property {string}   category         - "tops"|"bottoms"|"outerwear"|"dress"|"shoes"|"bags"|"accessories"|"set"|"unknown"
 * @property {string}   [product_name]   - Korean product name from Musinsa
 * @property {string}   [brand_name]
 * @property {string}   [brand_id]
 * @property {number}   [price]          - final price (KRW)
 * @property {number}   [original_price]
 * @property {number}   [discount_ratio] - 0-100
 * @property {string}   [product_url]
 * @property {number}   [rank]           - Musinsa ranking position
 * @property {boolean}  needs_category_review
 */

/**
 * @typedef {Object} CoordiRecord
 * @property {string}   id
 * @property {"coordi"} type
 * @property {string}   source           - "musinsa_snap" | "pinterest_pin"
 * @property {string}   app_url          - Vite-served URL
 * @property {string}   original_path
 * @property {string}   processed_path
 * @property {"outfit"} category
 * @property {boolean}  face_detected
 * @property {boolean}  crop_applied
 * @property {number}   [face_count]
 * @property {number}   [crop_start_y]
 * @property {number[]} [original_size]  - [w, h]
 * @property {number[]} [cropped_size]   - [w, h]
 * @property {string}   [snap_url]       - Musinsa snap URL
 * @property {string}   [pin_url]        - Pinterest URL
 * @property {string}   [dominant_color] - hex color from Pinterest
 * @property {string}   [description]
 * @property {string}   [board_name]
 */

// ─── Internal caches ──────────────────────────────────────────────────────────

let _items  = null;
let _coordi = null;

function items() {
  if (!_items) _items = assetManifest.items ?? [];
  return _items;
}

function coordi() {
  if (!_coordi) _coordi = assetManifest.coordi ?? [];
  return _coordi;
}

// ─── Item queries ─────────────────────────────────────────────────────────────

/**
 * Return all usable item images.
 * @returns {ItemRecord[]}
 */
export function getItemImages() {
  return items();
}

/**
 * Return item images filtered by category.
 * @param {"tops"|"bottoms"|"outerwear"|"dress"|"shoes"|"bags"|"accessories"|"set"|"unknown"} category
 * @returns {ItemRecord[]}
 */
export function getItemsByCategory(category) {
  return items().filter((r) => r.category === category);
}

/**
 * Return item images matching a brand name (case-insensitive, partial match).
 * @param {string} brandQuery
 * @returns {ItemRecord[]}
 */
export function searchItemsByBrand(brandQuery) {
  const q = brandQuery.toLowerCase();
  return items().filter(
    (r) => r.brand_name?.toLowerCase().includes(q) ||
           r.brand_id?.toLowerCase().includes(q)
  );
}

/**
 * Return item images matching a product name keyword (case-insensitive).
 * @param {string} keyword
 * @returns {ItemRecord[]}
 */
export function searchItemsByName(keyword) {
  const q = keyword.toLowerCase();
  return items().filter((r) => r.product_name?.toLowerCase().includes(q));
}

/**
 * Return N random item images, optionally filtered by category.
 * @param {number}  count
 * @param {string}  [category]
 * @returns {ItemRecord[]}
 */
export function getRandomItems(count, category) {
  const pool = category ? getItemsByCategory(category) : items();
  return shuffleSlice(pool, count);
}

/**
 * Return a single item image by its id (file stem).
 * @param {string} id
 * @returns {ItemRecord|undefined}
 */
export function getItemById(id) {
  return items().find((r) => r.id === id);
}

/**
 * Return all available item categories with counts.
 * @returns {{ category: string, count: number }[]}
 */
export function getItemCategoryStats() {
  const counts = {};
  items().forEach((r) => {
    counts[r.category] = (counts[r.category] ?? 0) + 1;
  });
  return Object.entries(counts)
    .map(([category, count]) => ({ category, count }))
    .sort((a, b) => b.count - a.count);
}

// ─── Coordi queries ───────────────────────────────────────────────────────────

/**
 * Return all usable coordi/style images.
 * @returns {CoordiRecord[]}
 */
export function getCoordinateImages() {
  return coordi();
}

/**
 * Return N random coordi images.
 * @param {number} count
 * @param {{ source?: "musinsa_snap"|"pinterest_pin" }} [options]
 * @returns {CoordiRecord[]}
 */
export function getRandomCoordi(count, options = {}) {
  let pool = coordi();
  if (options.source) {
    pool = pool.filter((r) => r.source === options.source);
  }
  return shuffleSlice(pool, count);
}

/**
 * Return coordi images from Musinsa snaps only.
 * @returns {CoordiRecord[]}
 */
export function getMusinssaSnaps() {
  return coordi().filter((r) => r.source === "musinsa_snap");
}

/**
 * Return coordi images from Pinterest pins only.
 * @returns {CoordiRecord[]}
 */
export function getPinterestPins() {
  return coordi().filter((r) => r.source === "pinterest_pin");
}

/**
 * Return a single coordi image by its id.
 * @param {string} id
 * @returns {CoordiRecord|undefined}
 */
export function getCoordiById(id) {
  return coordi().find((r) => r.id === id);
}

// ─── Mixed / utility queries ──────────────────────────────────────────────────

/**
 * Build a combined feed of item + coordi records, useful for discovery feeds.
 * Interleaves coordi and item images.
 * @param {{ itemCount?: number, coordiCount?: number }} [options]
 * @returns {(ItemRecord|CoordiRecord)[]}
 */
export function buildDiscoveryFeed({ itemCount = 20, coordiCount = 30 } = {}) {
  const selectedItems  = getRandomItems(itemCount);
  const selectedCoordi = getRandomCoordi(coordiCount);
  return interleave(selectedCoordi, selectedItems);
}

/**
 * Return pipeline metadata (generation time, stats, etc.).
 */
export function getPipelineMeta() {
  return {
    meta:  assetManifest._meta,
    stats: assetManifest.stats,
  };
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/**
 * Deterministically shuffle an array using Fisher-Yates (seedless — varies per session).
 * Returns a new array of up to `count` elements.
 */
function shuffleSlice(arr, count) {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, count);
}

/**
 * Interleave two arrays: a, b, a, b, …
 */
function interleave(a, b) {
  const result = [];
  const len = Math.max(a.length, b.length);
  for (let i = 0; i < len; i++) {
    if (i < a.length) result.push(a[i]);
    if (i < b.length) result.push(b[i]);
  }
  return result;
}
